name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make
      run: make

    - name: Upload
      uses: actions/upload-artifact@v3.0.0
      with:
        name: hextoggle-macos-x64
        path: build/hextoggle
